# Use the base image mysql:latest
FROM mysql:8.0

# Set environment variables 
ENV MYSQL_DATABASE=nutritionalkitchen
ENV MYSQL_ROOT_PASSWORD=password

# Copy custom scripts or configuration files from your host to the container
COPY ./script-ini.sql /docker-entrypoint-initdb.d/